### ISSUE TITLE
Mac操作系统下BUG

### ISSUE THREAD

**Issue by ElfStudio** [xtoolbox/lckiconverter#3]
Mac 系统中 Ctrl + 鼠标点击等于鼠标右键点击，导致无法正确将元件加入下载列表，建议参考 lcead 设置，Mac 系统使用 command 按键替代 Ctrl 按键。

我下载了源码自己修改后使用正常，改动很小，就不PR了，建议进行优化，谢谢。

mac下可以使用 MouseEvent.metaKey 判断，参考文档如下：
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey

**Comment by xtoolbox** [comment]
代码中增加了对metaKey的检查

**Comment by ElfStudio** [comment]
感谢及时修复
