### ISSUE TITLE
沉板元件(USB Type C)的使用方法疑问

### ISSUE THREAD

**Issue by xiaolanglanglang** [xtoolbox/lckiconverter#4]
立创 EDA 中有些元件是可以在板上挖槽的, 例如 TYPE-C-31-M-28, 供应商编号 C961762
在 KiCAD 中无法正确的预览 3D 效果, 看起来并没有对 PCB 做处理, 请问一下这是 KiCAD 的问题吗?

感谢您的插件, 它还是很好用的.

当预览时它还会让 KiCAD 弹窗提示:

kicad Information
Unable to find segment with an endpoint of (116.1593 mm, 115.3592 mm).

Cannot determine the board outline.

**Comment by xiaolanglanglang** [comment]
上面的 Type-C 元件生成的封装, 4 个引脚焊盘是椭圆形的, 焊盘的 Hole size X 和 Hole size Y 反了

**Comment by xtoolbox** [comment]
> 上面的 Type-C 元件生成的封装, 4 个引脚焊盘是椭圆形的, 焊盘的 Hole size X 和 Hole size Y 反了

感谢你的反馈。
关于挖槽的问题，这个封装在KiCad是预览的时候的确是有问题，但是放在电路板中的时候，就正确了。这是因为：
 KiCad的封闭编辑器不支持Edge.Cuts层，不能直接编辑。KiCad(5.x版本)的PCB引擎对多连通域图像处理有问题。
下面报的错是因为嘉立创在做封装的时候，额外画了一个边框层的线（在标准版中为紫色的线）造成Edge.Cuts层不闭合。在KiCad中或LCEDA中删掉这个额外的线就可不会报错了。这个是嘉立创做封装的问题，已经用槽孔描述挖空区域了，不应该在画额外的边框层线条。

关于椭圆形焊盘的方向问题，在最新的1.3版本中已经修正。

**Comment by xiaolanglanglang** [comment]
您好，我刚刚又进行了一下测试，我从专业版导出的模块椭圆焊盘依然有问题

我已确认我使用的版本为最新版

**Comment by xtoolbox** [comment]
> 您好，我刚刚又进行了一下测试，我从专业版导出的模块椭圆焊盘依然有问题
> 
> 我已确认我使用的版本为最新版

专业版确实有这个问题，孔的旋转参数被忽略了

**Comment by xiaolanglanglang** [comment]
我使用最新的代码进行了测试, 焊盘的位置是正确的了, 感谢作者.
期待作者更新到商店中.
